#!/usr/bin/env bash
# Re-resolve deploy/debs.lock.json: the Ubuntu packages the image adds on top of the CUDA base.
#
#   bazel run //deploy:relock_debs                       # resolve against today's snapshot
#   bazel run //deploy:relock_debs -- 20260928T000000Z   # resolve against a given snapshot
#
# WHY APT RUNS INSIDE THE BASE. The lock must hold exactly what the base lacks, no more: a layer
# that re-ships a package the base already has (libc6, libssl3t64) would overwrite the base's copy
# with whatever version the resolver picked. Running apt against the pinned base's own dpkg state
# makes it compute that delta, the same set `apt-get install` would add in a Dockerfile.
#
# WHY SNAPSHOT URLS. archive.ubuntu.com drops a -updates version from the pool once it is
# superseded, so a lock of archive URLs breaks within weeks. snapshot.ubuntu.com serves the archive
# as it was at a timestamp, forever, so the lock stays fetchable and the sha256 stays meaningful.
#
# Needs podman (the base image is pulled by the digest in MODULE.bazel). Review the diff like code.
set -euo pipefail

: "${BUILD_WORKSPACE_DIRECTORY:?run this with bazel run //deploy:relock_debs}"
root="$BUILD_WORKSPACE_DIRECTORY"
snapshot="${1:-$(date -u +%Y%m%dT000000Z)}"
# The packages the image needs; their dependencies are resolved, not listed.
packages=(curl tini)

digest="$(sed -n '/name = "reactantserver_cuda_base"/,/^)/s/.*digest = "\(sha256:[0-9a-f]*\)".*/\1/p' "$root/MODULE.bazel")"
image="$(sed -n '/name = "reactantserver_cuda_base"/,/^)/s/.*image = "\([^"]*\)".*/\1/p' "$root/MODULE.bazel")"
[ -n "$digest" ] && [ -n "$image" ] || { echo "FAILED: no reactantserver_cuda_base pull in MODULE.bazel" >&2; exit 1; }
base="${image#index.}@$digest"
echo "==> resolving ${packages[*]} against $base at snapshot $snapshot"

out="$(mktemp)"
trap 'rm -f "$out"' EXIT
podman run --rm --pull=missing --entrypoint bash "$base" -c '
set -euo pipefail
snapshot="$1"; shift
# Every Ubuntu source, the security pocket included, read from the snapshot.
sed -i -E "s#https?://(archive|security)\.ubuntu\.com/ubuntu/?#https://snapshot.ubuntu.com/ubuntu/$snapshot/#" \
    /etc/apt/sources.list.d/ubuntu.sources
# The CUDA repository is not snapshotted and is not needed: nothing locked comes from it.
rm -f /etc/apt/sources.list.d/cuda*.list
apt-get update -qq >/dev/null
mkdir -p /tmp/debs && chown _apt /tmp/debs && cd /tmp/debs
apt-get install -s --no-install-recommends "$@" | sed -n "s/^Inst \([^ ]*\) (\([^ ]*\) .*/\1 \2/p" |
while read -r name version; do
    url="$(apt-get download --print-uris "$name=$version" | cut -d"'\''" -f2)"
    apt-get download -qq "$name=$version"
    sha="$(sha256sum ./*.deb | cut -d" " -f1)"
    rm -f ./*.deb
    printf "%s %s %s %s\n" "$name" "$version" "$url" "$sha"
done
' bash "$snapshot" "${packages[@]}" > "$out"

[ -s "$out" ] || { echo "FAILED: apt resolved nothing (already in the base?)" >&2; exit 1; }

{
    printf '{\n'
    printf '  "comment": "Generated by bazel run //deploy:relock_debs. Do not edit.",\n'
    printf '  "base": "%s",\n' "$digest"
    printf '  "snapshot": "%s",\n' "$snapshot"
    printf '  "requested": [%s],\n' "$(printf '"%s", ' "${packages[@]}" | sed 's/, $//')"
    printf '  "packages": [\n'
    n="$(wc -l < "$out")"
    i=0
    while read -r name version url sha; do
        i=$((i + 1))
        sep=","; [ "$i" -eq "$n" ] && sep=""
        printf '    {"name": "%s", "version": "%s", "url": "%s", "sha256": "%s"}%s\n' \
            "$name" "$version" "$url" "$sha" "$sep"
    done < "$out"
    printf '  ]\n'
    printf '}\n'
} > "$root/deploy/debs.lock.json"
cat "$out" | awk '{print "   ", $1, $2}'
echo "wrote $root/deploy/debs.lock.json"
